### ISSUE TITLE
Qt 5.15+

### ISSUE THREAD

**Issue by ikrivosheev** [RazrFalcon/resvg#294]
Hello, I can not build with Qt 5.15+.
Logs:
```
pikaur -Sy resvg
Caused by:
  process didn't exit successfully: `/tmp/makepkg/resvg/src/resvg-0.9.0/target/release/build/resvg-qt-71581e8be6bf7b3e/build-script-build` (exit code: 1)
--- stdout
cargo:rustc-link-lib=Qt5Gui
cargo:rustc-link-lib=Qt5Core
TARGET = Some("x86_64-unknown-linux-gnu")
OPT_LEVEL = Some("3")
HOST = Some("x86_64-unknown-linux-gnu")
CXX_x86_64-unknown-linux-gnu = None
CXX_x86_64_unknown_linux_gnu = None
HOST_CXX = None
CXX = None
CXXFLAGS_x86_64-unknown-linux-gnu = None
CXXFLAGS_x86_64_unknown_linux_gnu = None
HOST_CXXFLAGS = None
CXXFLAGS = Some("-O2 -pipe -fno-plt")
CRATE_CC_NO_DEFAULTS = None
DEBUG = Some("false")
CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
running: "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-O2" "-pipe" "-fno-plt" "-I" "cpp" "-I" "/usr/include/qt/QtGui" "-I" "/usr/include/qt" "-I" "/usr/include/qt/QtCore" "-std=c++11" "-o" "/tmp/makepkg/resvg/src/resvg-0.9.0/target/release/build/resvg-qt-99a0a220e57eb815/out/cpp/qt_capi.o" "-c" "cpp/qt_capi.cpp"
cargo:warning=cpp/qt_capi.cpp: In function ‘void qtc_qpainter_draw_text(qtc_qpainter*, double, double, const char*)’:
cargo:warning=cpp/qt_capi.cpp:176:18: error: aggregate ‘QPainterPath path’ has incomplete type and cannot be defined
cargo:warning=  176 |     QPainterPath path;
cargo:warning=      |                  ^~~~
cargo:warning=cpp/qt_capi.cpp: In function ‘void qtc_qpainter_reset_clip_path(qtc_qpainter*)’:
cargo:warning=cpp/qt_capi.cpp:220:44: error: invalid use of incomplete type ‘class QPainterPath’
cargo:warning=  220 |     PAINTER_CAST->setClipPath(QPainterPath(), Qt::NoClip);
cargo:warning=      |                                            ^
cargo:warning=In file included from /usr/include/qt/QtGui/qtransform.h:43,
cargo:warning=                 from /usr/include/qt/QtGui/qimage.h:48,
cargo:warning=                 from /usr/include/qt/QtGui/QImage:1,
cargo:warning=                 from cpp/qt_capi.cpp:2:
cargo:warning=/usr/include/qt/QtGui/qmatrix.h:54:7: note: forward declaration of ‘class QPainterPath’
cargo:warning=   54 | class QPainterPath;
cargo:warning=      |       ^~~~~~~~~~~~
cargo:warning=cpp/qt_capi.cpp: In function ‘qtc_qpainterpath* qtc_qpainterpath_create()’:
cargo:warning=cpp/qt_capi.cpp:242:65: error: invalid use of incomplete type ‘class QPainterPath’
cargo:warning=  242 |     return reinterpret_cast<qtc_qpainterpath*>(new QPainterPath());
cargo:warning=      |                                                                 ^
cargo:warning=In file included from /usr/include/qt/QtGui/qtransform.h:43,
cargo:warning=                 from /usr/include/qt/QtGui/qimage.h:48,
cargo:warning=                 from /usr/include/qt/QtGui/QImage:1,
cargo:warning=                 from cpp/qt_capi.cpp:2:
cargo:warning=/usr/include/qt/QtGui/qmatrix.h:54:7: note: forward declaration of ‘class QPainterPath’
cargo:warning=   54 | class QPainterPath;
cargo:warning=      |       ^~~~~~~~~~~~
cargo:warning=cpp/qt_capi.cpp: In function ‘void qtc_qpainterpath_move_to(qtc_qpainterpath*, double, double)’:
cargo:warning=cpp/qt_capi.cpp:247:14: error: invalid use of incomplete type ‘class QPainterPath’
cargo:warning=  247 |     PATH_CAST->moveTo(x, y);
cargo:warning=      |              ^~
cargo:warning=In file included from /usr/include/qt/QtGui/qtransform.h:43,
cargo:warning=                 from /usr/include/qt/QtGui/qimage.h:48,
cargo:warning=                 from /usr/include/qt/QtGui/QImage:1,
cargo:warning=                 from cpp/qt_capi.cpp:2:
cargo:warning=/usr/include/qt/QtGui/qmatrix.h:54:7: note: forward declaration of ‘class QPainterPath’
cargo:warning=   54 | class QPainterPath;
cargo:warning=      |       ^~~~~~~~~~~~
cargo:warning=cpp/qt_capi.cpp: In function ‘void qtc_qpainterpath_line_to(qtc_qpainterpath*, double, double)’:
cargo:warning=cpp/qt_capi.cpp:252:14: error: invalid use of incomplete type ‘class QPainterPath’
cargo:warning=  252 |     PATH_CAST->lineTo(x, y);
cargo:warning=      |              ^~
cargo:warning=In file included from /usr/include/qt/QtGui/qtransform.h:43,
cargo:warning=                 from /usr/include/qt/QtGui/qimage.h:48,
cargo:warning=                 from /usr/include/qt/QtGui/QImage:1,
cargo:warning=                 from cpp/qt_capi.cpp:2:
cargo:warning=/usr/include/qt/QtGui/qmatrix.h:54:7: note: forward declaration of ‘class QPainterPath’
cargo:warning=   54 | class QPainterPath;
cargo:warning=      |       ^~~~~~~~~~~~
cargo:warning=cpp/qt_capi.cpp: In function ‘void qtc_qpainterpath_curve_to(qtc_qpainterpath*, double, double, double, double, double, double)’:
cargo:warning=cpp/qt_capi.cpp:258:14: error: invalid use of incomplete type ‘class QPainterPath’
cargo:warning=  258 |     PATH_CAST->cubicTo(x1, y1, x2, y2, x, y);
cargo:warning=      |              ^~
cargo:warning=In file included from /usr/include/qt/QtGui/qtransform.h:43,
cargo:warning=                 from /usr/include/qt/QtGui/qimage.h:48,
cargo:warning=                 from /usr/include/qt/QtGui/QImage:1,
cargo:warning=                 from cpp/qt_capi.cpp:2:
cargo:warning=/usr/include/qt/QtGui/qmatrix.h:54:7: note: forward declaration of ‘class QPainterPath’
cargo:warning=   54 | class QPainterPath;
cargo:warning=      |       ^~~~~~~~~~~~
cargo:warning=cpp/qt_capi.cpp: In function ‘void qtc_qpainterpath_close_path(qtc_qpainterpath*)’:
cargo:warning=cpp/qt_capi.cpp:263:14: error: invalid use of incomplete type ‘class QPainterPath’
cargo:warning=  263 |     PATH_CAST->closeSubpath();
cargo:warning=      |              ^~
cargo:warning=In file included from /usr/include/qt/QtGui/qtransform.h:43,
cargo:warning=                 from /usr/include/qt/QtGui/qimage.h:48,
cargo:warning=                 from /usr/include/qt/QtGui/QImage:1,
cargo:warning=                 from cpp/qt_capi.cpp:2:
cargo:warning=/usr/include/qt/QtGui/qmatrix.h:54:7: note: forward declaration of ‘class QPainterPath’
cargo:warning=   54 | class QPainterPath;
cargo:warning=      |       ^~~~~~~~~~~~
cargo:warning=cpp/qt_capi.cpp: In function ‘void qtc_qpainterpath_set_fill_rule(qtc_qpainterpath*, FillRule)’:
cargo:warning=cpp/qt_capi.cpp:268:14: error: invalid use of incomplete type ‘class QPainterPath’
cargo:warning=  268 |     PATH_CAST->setFillRule(Qt::FillRule(rule));
cargo:warning=      |              ^~
cargo:warning=In file included from /usr/include/qt/QtGui/qtransform.h:43,
cargo:warning=                 from /usr/include/qt/QtGui/qimage.h:48,
cargo:warning=                 from /usr/include/qt/QtGui/QImage:1,
cargo:warning=                 from cpp/qt_capi.cpp:2:
cargo:warning=/usr/include/qt/QtGui/qmatrix.h:54:7: note: forward declaration of ‘class QPainterPath’
cargo:warning=   54 | class QPainterPath;
cargo:warning=      |       ^~~~~~~~~~~~
cargo:warning=cpp/qt_capi.cpp: In function ‘void qtc_qpainterpath_destroy(qtc_qpainterpath*)’:
cargo:warning=cpp/qt_capi.cpp:273:5: warning: possible problem detected in invocation of ‘operator delete’ [-Wdelete-incomplete]
cargo:warning=  273 |     delete PATH_CAST;
cargo:warning=      |     ^
cargo:warning=cpp/qt_capi.cpp:11:19: warning: invalid use of incomplete type ‘class QPainterPath’
cargo:warning=   11 | #define PATH_CAST reinterpret_cast<QPainterPath*>(c_pp)
cargo:warning=      |                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cargo:warning=cpp/qt_capi.cpp:273:12: note: in expansion of macro ‘PATH_CAST’
cargo:warning=  273 |     delete PATH_CAST;
cargo:warning=      |            ^~~~~~~~~
cargo:warning=In file included from /usr/include/qt/QtGui/qtransform.h:43,
cargo:warning=                 from /usr/include/qt/QtGui/qimage.h:48,
cargo:warning=                 from /usr/include/qt/QtGui/QImage:1,
cargo:warning=                 from cpp/qt_capi.cpp:2:
cargo:warning=/usr/include/qt/QtGui/qmatrix.h:54:7: note: forward declaration of ‘class QPainterPath’
cargo:warning=   54 | class QPainterPath;
cargo:warning=      |       ^~~~~~~~~~~~
cargo:warning=cpp/qt_capi.cpp:273:5: note: neither the destructor nor the class-specific ‘operator delete’ will be called, even if they are declared when the class is defined
cargo:warning=  273 |     delete PATH_CAST;
cargo:warning=      |     ^
```
